README.md

make is easier to install theme

doc: Add theme installation instructions

---

layouts/partials/header.html
layouts/partials/menu.html

Reverts matcornic/hugo-theme-learn#5

Revert "Menu generation using Content file instead directories"

---

static/css/hugo-theme.css
static/css/theme.css

Add style for this shortcode: https://gohugo.io/extras/shortcodes/#figure

feat: style Hugo figure shortcode

---

static/css/theme.css

Feel free to suggest another color :)

feat: Change the default code color

---

layouts/partials/menu.html
layouts/shortcodes/children.html

I believe that this should solve [this](https://github.com/matcornic/hugo-theme-learn/issues/79) issue

Bug fix in sidebar menu and children description generation

---

layouts/404.html
layouts/partials/search.html
layouts/shortcodes/attachments.html

Don't bake in the base url to generated sites.

Use `relURL`  where possible

---

exampleSite/config.toml

Align 'More' items' icons with full-width (`fa-fw`) Font-Awesome class.

doc: Keep icons aligned

---

static/js/hugo-learn.js

fix #77 : no wrap images that already wrapped

---

exampleSite/content/basics/installation/_index.en.md

Fixed spelling and awkward phrasing to make it read better.

Clean up the English language phrasing

---

archetypes/chapter.md
archetypes/default.md
exampleSite/content/cont/archetypes.en.md
exampleSite/content/cont/archetypes.fr.md

https://github.com/gohugoio/hugo/commit/863a812e07193541b42732b0e227f3d320433f01

TranslationBaseName replaced for Name on archetypes template

---

netlify.toml

Set build steps in config

---

README.md

HTTPS link to learn.getgrav.org

---

layouts/partials/search.html

This fixes the close/cancel search icon not showing

---

i18n/nl.toml

This PR adds Dutch translation to the theme.
Feel free to check the translations. I'm a native speaker, but in no way a professional translator.

Dutch i18n

---

exampleSite/content/shortcodes/mermaid.en.md
exampleSite/content/shortcodes/mermaid.fr.md
static/js/hugo-learn.js

This fix issue ##225
Thank you,

Render the ```mermaid blocks into graphs

---

exampleSite/content/cont/markdown.en.md

Fix type lines 364 and 369

---

i18n/ja.toml
i18n/zh-cn.toml

Credits to @miekof and @liushilive, who added these translations to the Selenium docs [project](https://github.com/SeleniumHQ/docs/tree/gh-pages/docs_source_files/themes/hugo-theme-learn/i18n)

Add jp and zh cn

---

i18n/ru.toml

Added:
- Russian RU translation.

Added Russian translation

---

exampleSite/content/cont/pages/_index.fr.md

Corrections de plusieurs erreurs typo ! :p

Fix: typos

---

exampleSite/content/shortcodes/notice.en.md

I guess there has been an incorrect copy paste.

Incorrect english in notice documentation

---

layouts/partials/menu.html
netlify.toml

Build fail when using Hugo 0.71.1.
Related issue: #401

can't give argument to non-function not .Params.hidden

---

static/js/hugo-learn.js

fix null pointer when no params on image url

---

exampleSite/content/shortcodes/children/_index.en.md

HTML does not seem to display properly in the table

Fix children shortcode table

---

layouts/shortcodes/attachments.html

I think need a div end tag at line 33 instead of a div start tag.

fix: closing div tag

---

exampleSite/config.toml
exampleSite/content/basics/configuration/_index.en.md
layouts/partials/header.html

Add the titleSeparator parameter.

---

exampleSite/content/shortcodes/tabs.en.md
layouts/partials/header.html
layouts/shortcodes/tab.html
layouts/shortcodes/tabs.html
static/css/tabs.css
static/js/learn.js

We recently decided to add this to our internal documentation. I thought other people might find it useful, too. 
I do speak some French but I'd still leave the translation up to someone else.
closes #70 
Btw. the code was inspired by solutions from:
https://github.com/gohugoio/hugoDocs/
https://github.com/kubernetes/website/
https://www.mediaevent.de/tutorial/css-tabs.html

Implement tab views

---

exampleSite/content/basics/installation/_index.en.md

https://github.com/matcornic/hugo-theme-learn/issues/528

Add GA Analytics notice in docs english
