matcornic/hugo-theme-learn

layouts/partials/header.html
layouts/partials/menu.html
static/css/theme.css

Added the missing code to show the checkmark on visited links on sidebar. All js code was already in place, just missing some html.

Add Checkmark On visited Links

---

layouts/partials/header.html
layouts/partials/menu.html

This implementation use the sample i posted on #2 with a few changes:
only activated when 
`createFromSiteMenusMain = true `
on `config.toml`
Need to add to the archetypes the correct information to create the menu, need suggestions on how we change this.
we can create them on the content page
chapter.md
```yaml
--- 
title : "Title to show"
prev: /prev/path
next: /next/path
chapter: true 
menu:
main:
identifier : "Unique_ID_OF_PAGE"
weight: 5
name : "Title to show"
pre : '<b>1.</b>'
---
```
default.md
```yaml
---
title: What is this Hugo theme ?
prev: /prev/path
next: /next/path
menu:
main:
identifier : "Unique_ID_OF_PAGE"
parent: 'Unique_ID_OF_PARENT'
weight: 5
name : "What is this Hugo theme"
---
```
or on the config.toml 
```yaml
--- 
menu:
main:
- Name: "about hugo"
Pre: "<i class='fa …
```

Menu generation using Content file instead directories

---

layouts/partials/menu.html

This is how I solved issues (https://github.com/matcornic/hugo-theme-learn/issues/2) with menu ordering for one of my sites.
Example `tree content`:
```
content/
├── about
│   ├── content.md
│   ├── index.md
├── bar
│   ├── index.md
│   └── mode_bar.md
├── foo
│   ├── foo2.md
│   └── index.md
└── introduction
├── index.md
└── blabla.md
```
Now if I want to have my menu ordered as:
1. about
2. introduction
3. foo
4. bar
all I need is to add 2 lines in `config.toml`:
```
createFromSiteMenusMain = true
[params]
menu = [ "about", "introduction", "foo", "bar" ]
```

Menu ordering and definition in config.toml

---

layouts/partials/header.html

Hugo on Windows returns backslash (`\`) instead of forward slash (`/`) for file paths. This fixes the computed URL to edit a page.

Fix URL for 'Edit this page' on Windows

---

layouts/partials/menu-footer.html
layouts/partials/menu.html

Extracted menu footer content to separate partial file named ``menu-footer.html``, so this easily can be changed or overwritten without the need to overwrite the entire ``menu.html`` file.
```html
<section id="footer">
{{ partial "menu-footer.html" . }}
</section>
```

Extracted menu footer content to separate partial file

---

archetypes/chapter.md
archetypes/default.md
layouts/_default/list.html
layouts/partials/footer.html
layouts/partials/header.html
layouts/partials/menu.html
theme.toml

This PR enables using `_index.md` pages for chapters and adds automatic generation of navigation arrows (#22). I tried *hard* to keep this backwards-compatible, and it seems to be, for the most part. A caveat is that automatic navigation ~errors~ arrows may not work for legacy structure (with `index.md` pages) 100% of the time (although a hack to *make* it work most of the time is included).
Changes:
* Chapter pages should now be named `_index.md`
* `chapter: true` is unnecessary for `_index.md` files
* New site parameter `autoNav` enables automatic navigation arrows. `prev` and `next` page metadata options are still supported as overrides. Setting `prev: false` or `next: false` disables an arrow on that page.
* `menu` site parameter is superseded by weight-based ordering of `_index.md` …

Use index pages + automatic navigation arrows

---

layouts/partials/header.html
static/js/hugo-learn.js

When the top bar reaches the top, the heading jumps as the original top-bar is removed from the DOM. (Scroll this page: https://matcornic.github.io/hugo-learn-doc/basics/installation/ for an example). 
This is due to a a slight nuance of how Sticky-Kit works. To prevent this, I have updated the HTML and JS related to the top bar as suggested here: https://github.com/leafo/sticky-kit/wiki/Troubleshooting#my-adsiframeplugin-based-content-flashes-or-get-removed-when-it-becomes-sticky

Fix sticky header jumpiness

---

static/js/learn.js

Currently, when you use an anchor link, such as from the TOC box, or returning from a footnote, the actual anchor gets pushed behind the breadcrumbs/top-bar. 
This change fixes that using some jquery and the code from [https://stackoverflow.com/a/13067009/28106](https://stackoverflow.com/a/13067009/28106).
This could technically be fixed with pure CSS (https://stackoverflow.com/a/13184714/28106), but it would require adding a class to every tag that used anchors.

Fix anchor scrolling that hides behind top nav bar

---

layouts/shortcodes/mermaid.html

Fixes alignment behavior in the short code

Remove white space from `align` parameter

---

exampleSite/content/basics/installation/_index.en.md

Not sure it's the best place to go in the documentation, but I thought this might prevent new Hugo user to wonder why no content was listed.

Added info about 'draft:true'

---

exampleSite/content/cont/pages/_index.en.md
layouts/partials/menu.html

Right now the `title` frontmatter argument is used both for the page title and for its entry in the menu hierarchy.
This makes it hard to use descriptive titles. Take the following hierarchy for example:
- Install
- Linux
- ...
The `Linux` page would have to use that exact title. A better (and more descriptive) page title would be *Install on Linux* (but that's a little long for the menu).
This patch will use the official `linkTitle` if present.
And if the custom `menuTitle` is defined, that one will be used instead.

Added a `menuTitle` attribute to partials/menu.html

---

static/js/learn.js

Don't add class `highlight` to links to footnotes. With class `highlight`, for the following Markdown:
A sentence with a footnote.[^target]
, the footnote may be rendered on the next line, 
, due to setting `display: inline-block;`in the following rule in `hugo-theme.css`:
```
#body a.highlight {
line-height: 1.1;
display: inline-block;
}
```
When the footnote link don't have the highlight class the footnote number will always be rendered on the same line as the preceding `footnote.`.

Fix: No class highlight for link to footnote

---

layouts/partials/menu.html

Removing class="" because it does not add a whole lot
Removing role="" because it is invalid HTML (cannot be empty) and generates HTML-errors in validators.

role="" is invalid

---

i18n/tr.toml

Made this lil' file for a project, figured I should send it upstream.

Add Turkish i18n config file

---

exampleSite/config.toml
exampleSite/content/basics/configuration/_index.en.md
layouts/partials/footer.html
layouts/partials/header.html

Continues from #137. I accidentally broke that one.
> Can we merge this in as a sitewide setting and add per-page override to the backlog? I've tried implementing this but can't solve without having both a disableNextPrev and a enableNextPrev.

RETRY - Params to turn off next/previous page - and breadcrumb

---

layouts/partials/search.html

This doesn't change functionality but could aid with accessibility and is more semantically correct.

Use correct input type for search

---

static/mermaid/mermaid.css
static/mermaid/mermaid.dark.css
static/mermaid/mermaid.forest.css

Hi @matcornic,
Thanks again for this awesome theme! 
As per the referenced https://github.com/matcornic/hugo-theme-learn/issues/168, we can create clickable nodes in mermaid as per the demo site, but the cursor is not being styled correctly. This sorts that out.
- add CSS ruleset for clickable nodes
- replace JS with latest minified from mermaidjs.github.io

fix clickable nodes style in mermaid

---

static/js/learn.js

If input field is in focus, keydown event to trigger navigation change should
not fire. User should expect cursor to stay in input field when using arrow keys.
Fixes #216

prevents left and right keydown in input fields

---

layouts/partials/menu.html

Hey, @matcornic -- I just wanted to say that this is a beautiful HUGO template - thank you for providing this.
I'm seeing issues where the check icon is not rendered. It seems like it this `<i></i>` element was mistakenly missing the additional class required in order for it to actually render the font-awesome check icon. So, I added the `fa-check` class locally and now it works as expected.

Update menu.html to include the check icon

---

static/js/learn.js

Preventing left/right arrow key navigation in textareas. This takes advantage of the existing code added by #219.
Fixes #240.

Preventing left/right arrow key navigation in textareas

---

layouts/partials/favicon.html

`image/x-icon` is only for .ico files. `image/png` should be used for .png

remove duplicate icon and fix incorrect favicon type

---

layouts/partials/menu.html

When the ``baseURL`` is not ``/`` using ``$translation.URL`` is ignoring the ``baseURL``.
In order to sort this behavior, ``$translation.Permalink`` is working just fine.

Fix translation when using a custom baseURL

---

exampleSite/content/cont/tags.en.md
exampleSite/content/cont/tags.fr.md
layouts/_default/list.html
layouts/partials/header.html
layouts/partials/tags.html
static/css/tags.css
static/css/theme-blue.css
static/css/theme-green.css
static/css/theme-red.css
static/css/theme.css

I love your theme, so I added the support for one of the default taxonomy in GoHugo : tags. 
I also added documentation in the exampleSite, and the theme variants. 
I only doubt about the CSS, if anyone have a better idea don't hesitate :-)

Added support for tags

---

layouts/shortcodes/children.html

As Explained in [PR 194](https://github.com/matcornic/hugo-theme-learn/pull/194), there is a bug in the children shortcode where it only returns the top level.
This pull request is to fix this issue.
Unlike PR 194, this fix works on 0.26

Fix issue where "children" shortcode only shows top level.

---

exampleSite/content/basics/installation/_index.en.md
exampleSite/content/basics/installation/_index.fr.md
exampleSite/content/basics/requirements/_index.en.md
exampleSite/content/basics/requirements/_index.fr.md
exampleSite/content/basics/style-customization/_index.en.md
exampleSite/content/basics/style-customization/_index.fr.md
exampleSite/content/cont/i18n/_index.en.md
exampleSite/content/cont/i18n/_index.fr.md
exampleSite/content/cont/pages/_index.en.md
exampleSite/content/cont/pages/_index.fr.md
layouts/shortcodes/attachments.html
layouts/shortcodes/button.html
layouts/shortcodes/children.html
layouts/shortcodes/expand.html
layouts/shortcodes/mermaid.html
layouts/shortcodes/notice.html
netlify.toml

Fixes #272 
Fixes #273 
Fixes #282
This PR simply marks all shortcodes to use hugo's old rendering mechanism for shortcodes.

Make shortcodes & example site compatible with Hugo v0.55

---

layouts/partials/header.html

It's not needed on HTML5.
REF: https://google.github.io/styleguide/htmlcssguide.html#type_Attributes

remove unneeded  type="text/css"

---

layouts/404.html

Fix invalid HTML in 404 template.

---

i18n/ar.toml
i18n/de.toml
i18n/hi.toml

Added:  
- German 🇩🇪and Arabic translation.
- Hindi language🇮🇳 file

Added German and Arabic translation

---

layouts/_default/list.html
layouts/partials/footer.html
layouts/partials/header.html
layouts/partials/menu.html
layouts/shortcodes/children.html
layouts/shortcodes/ref.html
layouts/shortcodes/relref.html

There is still a warning about using .File on a zero object, but as far as I can tell it doesn't affect page generation.

Fix deprecated .Hugo, .UniqueID and .URL references

---

layouts/partials/footer.html

`<script src="{{"js/html5shiv-printshiv.min.js" | relURL}}{{ if not .Site.Params.disableAssetsBusting }}?{{ now.Unix }}{{ end }}"></script>`
This was only ever needed for IE8 (which is not supported with this theme since it uses a newer version of jQuery).
Furthermore it should be loaded in the head anyway. IE9 and later supports HTML5 tags and does not need this polyfill at all.
REF:
- https://github.com/aFarkas/html5shiv
- https://getbootstrap.com/docs/3.4/getting-started/#template

remove html5shiv

---

static/css/theme.css

The current `nucleus.css` adds `color: inherit` for `<select>`. However, in Google Chrome, this also affects the `<option>` elements. Thus if the parent text color is white, then the option color will be white too, making the option text invisible against its default white background.
This PR simply adds a `color: initial` to the general `theme.css`.

fix select option color in Chrome

---

exampleSite/content/cont/markdown.en.md
static/js/hugo-learn.js

This PR is to handle #322 together with changes in the documentation. 
If an image has the HTTP parameter featherlight set to false, it will not add the data attributes needed to for the featherlight JS plugin.

Added flag to turn off image featherlight

---

layouts/partials/menu.html

Fixes this warning:
```
WARN 2020/02/11 23:27:49 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
```
Related issues: #329, #350

Fix .File.UniqueID on zero object warning

---

exampleSite/content/basics/installation/_index.en.md

Since the old link redirects to "Hugo Modules" documentation, which isn't fitting for this kind of theme, I changed it to the short tutorial in the getting started guide. Not perfect but better than having a mismatching guide, confusing users (such as myself).

Updated theme installation documentation link.

---

exampleSite/content/basics/configuration/_index.en.md
exampleSite/content/basics/configuration/_index.fr.md
layouts/partials/header.html

Previously adding custom css files would require the end user to copy
the header or footer partial into their overrides. They would then
need to maintain that partial into the future.
This config allows a user to provide a list of custom css files to load
into the theme, meaning they do not need to clone the partial.
```
[params]
custom_css = ["css/foo.css", "css/bar.css"]
```
Inspiration taken from https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/4

Allow custom css files to be loaded by configuration

---

exampleSite/content/cont/markdown.en.md
exampleSite/content/cont/syntaxhighlight.en.md

Add additional documentation for code highlighting

---

static/css/theme.css

Make the "copy to clipboard" button more obvious by making the background a lighter color, and changing the hover image to match the color of the standard link hover color.

Make copy to clipboard button more obvious, make hover match link color

---

static/js/learn.js

Hi. Thanks for this beautiful theme. I however noticed something odd, which is that this `adjustForScrollbar` function does not seem to be doing anything under regular usage, but it is getting in my way when I try to customize my home page. I'll explain.
The code adds a ~15px margin to the right navigation arrow then the `#body-inner` height is near the same height as `#body`. The intent appears to be to detect when the scrollbar is present on-screen, but because `#body` is a div that contains `#body-inner`, and therefore content added to `#body-inner` affects the height  of both divs, this condition will continue to always evaluate to `false`. I checked this on pages that required scrolling, and sure enough the margin of the right-nav was still 0.
So for the above reason I believe the …

Remove code that adjusts navigation margin

---

layouts/_default/list.html
layouts/partials/header.html

without my fix, tags page are broken.
If you run `hugo serve`
There is no reference in page : 
TaxonomyTerm is replace by term
see https://github.com/sjroe/hugo-theme-learn/commit/bf74d9e81c503ec24e44fccde449f58dfed259c9 #389

fix: change taxonomy term and use taxonomy name

---

i18n/ar.toml
i18n/de.toml
i18n/en.toml
i18n/es.toml
i18n/fr.toml
i18n/hi.toml
i18n/id.toml
i18n/ja.toml
i18n/nl.toml
i18n/pt.toml
i18n/ru.toml
i18n/tr.toml
i18n/zh-cn.toml
layouts/shortcodes/attachments.html

This PR is for minor **i18n** fix with regards to the binary prefix as mentioned in PR #299 
Based on the suggestion there and the [link](https://mle2f.wordpress.com/2008/11/14/unites-binaires/), kilobyte binary prefix will be **"ko"** for **Fr** while **En** will be **"kb"**.

Added binary prefix for kilobyte using i18n

---

layouts/shortcodes/children.html

The `children` shortcode shouldn't call `.Inner` as it doesn't have nested content. A consequence of calling `.Inner` is that Hugo takes the rest of the page as the inner content displaying it incorrectly.
See as an example: https://learn.netlify.app/en/shortcodes/children/
The page stops abruptly with `{{% children description="true" %}}` with the rest of the page content missing. While the HTML source shows `` in place of the missing content.

Remove .Inner from children shortcode

---

static/css/hugo-theme.css

Fixes #378 and works properly with any number of levels in the TOC:

Fix TOC indentation

---

layouts/partials/menu.html

Without this fix if you only have hidden pages in your sub-menu you will get an empty `<ul></ul>` that makes the menu entry a little bit taller than the others

Don't count hidden pages for the sub-menus
